/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectafterupdatev1.pkg2;

import java.util.*;
import javax.swing.DefaultComboBoxModel;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;

/**
 *
 * @author Bassel
 */
public class GameOptions extends javax.swing.JFrame {
    static Ship[] userships;
    static String Name;
    static String choosenfile;
    Boolean Loadgame=false;
     boolean[][] shipIsFound=new boolean[27][27];
    static boolean Cheatingenabled=false;
   static Integer Lengthoftheship=1,Widthoftheship=1;
   static Integer Turntimerset=10;
List<Integer> numberofrows=new ArrayList<Integer>();
List<Integer> ships=new ArrayList<Integer>();
List<Character> shipsColoumnsStart=new ArrayList<Character>();
List<Integer> shipsRowStart=new ArrayList<Integer>();
List<Integer> turntimer=new ArrayList<Integer>();
List<String> filesnames=new ArrayList<String>();

Integer z=0;
    /**
     * Creates new form GameOptions
     */
   public void UpdateCompoBox(){
     ships.clear();
     shipsColoumnsStart.clear();
     shipsRowStart.clear();
     UpdateShipsRowAndColoumns();
      for(int i=1;i<=(int)column.getSelectedItem()*(int)row.getSelectedItem();i++){
           ships.add(i);
       }
       shipsnumber.setModel(new DefaultComboBoxModel(ships.toArray()));
       
   
   
   }
    public GameOptions() throws FileNotFoundException {
        
        userships=new Ship[1];
        initComponents();
        for(int i=1;i<=10;i++){
            turntimer.add(i);
        }
        turntime.setModel(new DefaultComboBoxModel(turntimer.toArray()));
        jDialog1.setSize(536, 212);
        jDialog1.setLocation(500,250);
        jDialog2.setSize(536, 212);
        jDialog2.setLocation(500,250);
        jTextField2.setText("Error no name found");
        for(int i=1;i<=20;i++)
        numberofrows.add(i);
        column.setModel(new DefaultComboBoxModel(numberofrows.toArray()));
        row.setModel(new DefaultComboBoxModel(numberofrows.toArray()));
        UpdateCompoBox();
        
       //fill the combo box with file names
        File f=new File(new File("").getAbsolutePath()+"\\src\\projectafterupdatev1\\pkg2\\filesNames");
        ObjectInputStream obj=null;
        try {
            obj = new ObjectInputStream(new FileInputStream(f));
            while (true){
                String temp=(String)obj.readObject();
                if(!Objects.equals(temp, null) || !!Objects.equals(temp, ""))
                filesnames.add(temp);
                
            }
                
        } catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
        }finally{
            try {
                obj.close();
            } catch (IOException ex) {
            }
        }
        jComboBox1.setModel(new DefaultComboBoxModel(filesnames.toArray()));
    }
    public void UpdateShipsRowAndColoumns(){
    
      for(int i=1;i<=(int)row.getSelectedItem();i++)
      {
          
          shipsRowStart.add(i);
      }
      for(int i=0;i<(int)column.getSelectedItem();i++){
          shipsColoumnsStart.add((char)(i+'a'));
      }
      X1.setModel(new DefaultComboBoxModel(shipsRowStart.toArray()));
      Y1.setModel(new DefaultComboBoxModel(shipsColoumnsStart.toArray()));
      X2.setModel(new DefaultComboBoxModel(shipsRowStart.toArray()));
      Y2.setModel(new DefaultComboBoxModel(shipsColoumnsStart.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jDialog2 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ShipsCounter = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Y1 = new javax.swing.JComboBox();
        Y2 = new javax.swing.JComboBox();
        row = new javax.swing.JComboBox();
        X1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        X2 = new javax.swing.JComboBox();
        column = new javax.swing.JComboBox();
        StartButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AddShip = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        shipsnumber = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        turntime = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LoadGame = new javax.swing.JButton();
        ScoreBoardbtn = new javax.swing.JButton();
        GamesReordsbtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jDialog1.setTitle("Error");
        jDialog1.setBackground(new java.awt.Color(255, 102, 51));
        jDialog1.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Error no ships found");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialog2.setTitle("Error");
        jDialog2.setBackground(new java.awt.Color(255, 102, 51));
        jDialog2.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(153, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Error no ships found");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Option");
        setBackground(new java.awt.Color(149, 230, 228));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X2");

        ShipsCounter.setEditable(false);
        ShipsCounter.setBackground(new java.awt.Color(102, 102, 102));
        ShipsCounter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ShipsCounter.setForeground(new java.awt.Color(255, 255, 255));
        ShipsCounter.setText("0");
        ShipsCounter.setBorder(null);
        ShipsCounter.setOpaque(false);
        ShipsCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipsCounterActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X1");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Y1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Start");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("End");

        Y1.setBackground(new java.awt.Color(0, 153, 153));
        Y1.setForeground(new java.awt.Color(255, 255, 255));
        Y1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Y1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Y2.setBackground(new java.awt.Color(0, 153, 153));
        Y2.setForeground(new java.awt.Color(255, 255, 255));
        Y2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Y2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        row.setBackground(new java.awt.Color(0, 153, 153));
        row.setForeground(new java.awt.Color(255, 255, 255));
        row.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        row.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowActionPerformed(evt);
            }
        });

        X1.setBackground(new java.awt.Color(0, 153, 153));
        X1.setForeground(new java.awt.Color(255, 255, 255));
        X1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        X1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grid Options");

        X2.setBackground(new java.awt.Color(0, 153, 153));
        X2.setForeground(new java.awt.Color(255, 255, 255));
        X2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        X2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X2ActionPerformed(evt);
            }
        });

        column.setBackground(new java.awt.Color(0, 153, 153));
        column.setForeground(new java.awt.Color(255, 255, 255));
        column.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        column.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        column.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnActionPerformed(evt);
            }
        });

        StartButton.setBackground(new java.awt.Color(0, 153, 153));
        StartButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StartButton.setForeground(new java.awt.Color(255, 255, 255));
        StartButton.setText("Start");
        StartButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("row");

        AddShip.setBackground(new java.awt.Color(0, 153, 153));
        AddShip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AddShip.setForeground(new java.awt.Color(255, 255, 255));
        AddShip.setText("Add");
        AddShip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddShipActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("column");

        shipsnumber.setBackground(new java.awt.Color(0, 153, 153));
        shipsnumber.setForeground(new java.awt.Color(255, 255, 255));
        shipsnumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shipsnumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        shipsnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipsnumberActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ships number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ships Locations");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Y2");

        jRadioButton1.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cheating");

        turntime.setBackground(new java.awt.Color(0, 153, 153));
        turntime.setForeground(new java.awt.Color(255, 255, 255));
        turntime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        turntime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        turntime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turntimeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Turn Time");

        UserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserName.setOpaque(false);
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Name");

        LoadGame.setBackground(new java.awt.Color(0, 153, 153));
        LoadGame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoadGame.setForeground(new java.awt.Color(255, 255, 255));
        LoadGame.setText("Load Previous Game");
        LoadGame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGameActionPerformed(evt);
            }
        });

        ScoreBoardbtn.setBackground(new java.awt.Color(0, 153, 153));
        ScoreBoardbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ScoreBoardbtn.setForeground(new java.awt.Color(255, 255, 255));
        ScoreBoardbtn.setText("ScoreBoard");
        ScoreBoardbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ScoreBoardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreBoardbtnActionPerformed(evt);
            }
        });

        GamesReordsbtn.setBackground(new java.awt.Color(0, 153, 153));
        GamesReordsbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GamesReordsbtn.setForeground(new java.awt.Color(255, 255, 255));
        GamesReordsbtn.setText("Games Records");
        GamesReordsbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GamesReordsbtn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                GamesReordsbtnAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        GamesReordsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamesReordsbtnActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10)
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel9)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(row, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(shipsnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(column, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jLabel3))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel7))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addComponent(turntime, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AddShip, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(ShipsCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(X1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(X2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Y2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreBoardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GamesReordsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipsnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(X1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddShip)
                    .addComponent(ShipsCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScoreBoardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GamesReordsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowActionPerformed
        // TODO add your handling code here:
        
        //shipsnumber.removeAllItems();
        UpdateCompoBox();
        repaint();
        
        
    }//GEN-LAST:event_rowActionPerformed

    private void X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_X2ActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        //hon bde shof 2za 3bakl alsfn
        if(Objects.equals(UserName.getText().toString(), ""))
            jDialog2.setVisible(true);
        else{
        if (z!=0 && z==shipsnumber.getSelectedItem()){
            synchronized(Projectafterupdatev12.gamewaiter){
          Projectafterupdatev12.gamewaiter.notifyAll();}
            //Projectafterupdatev12.gamewaiter.notifyAll();
            Lengthoftheship=(int)row.getSelectedItem();
            Widthoftheship=(int)column.getSelectedItem();
            this.setVisible(false);
            Turntimerset=(int)turntime.getSelectedItem();
            Name=UserName.getText().toString();
            Cheatingenabled=jRadioButton1.isSelected();
            
        }else
        {
            jTextField1.setText("Error no ships found");
            
            jDialog1.setVisible(true);
        }
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void ShipsCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipsCounterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShipsCounterActionPerformed

    private void shipsnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipsnumberActionPerformed
        // TODO add your handling code here:
        userships=new Ship[(int)shipsnumber.getSelectedItem()];
        shipIsFound=new boolean[1000][1000];
        z=0;
        ShipsCounter.setText(z.toString());
    }//GEN-LAST:event_shipsnumberActionPerformed

    private void columnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnActionPerformed
        // TODO add your handling code here
         //ships.clear();
       UpdateCompoBox();
        repaint();
       
    }//GEN-LAST:event_columnActionPerformed

    private void AddShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddShipActionPerformed
        // TODO add your handling code here:
        if (z<userships.length){
        String start,end;
        start=X1.getSelectedItem().toString()+Y1.getSelectedItem().toString();
        end=X2.getSelectedItem().toString()+Y2.getSelectedItem().toString();
        int first1=(start.charAt(0)-'1')+1;
        int second1=(start.charAt(1)-'a')+1;
         int first2=(end.charAt(0)-'1')+1;
        int second2=(end.charAt(1)-'a')+1;
        boolean dialogueNeeded=false;
        
        if(first1==first2){
          for(int i=Math.min(second1, second2);i<=Math.max(second1,second2);i++){
             if(shipIsFound[first1][i]){
             dialogueNeeded=true;
             }
          }
        }
        else if(second1==second2){
           for(int i=Math.min(first1, first2);i<=Math.max(first1,first2);i++){
             if(shipIsFound[i][second1]){
                  dialogueNeeded=true;
             }
          }
        }
        else{
          dialogueNeeded=true;
          
        }
        if(dialogueNeeded){
        jTextField1.setText("Error: please enter a valid location");
        jDialog1.setVisible(true);
        /// sHow  the dialogue and skip to the end of the 
        }
        else{
            if(first1==first2){
          for(int i=Math.min(second1, second2);i<=Math.max(second1,second2);i++){
             shipIsFound[first1][i]=true;
          }
        }
        else if(second1==second2){
           for(int i=Math.min(first1, first2);i<=Math.max(first1,first2);i++){
             shipIsFound[i][second1]=true;
          }
        }
        userships[z]=new Ship(start,end);
        z++;
        ShipsCounter.setText(z.toString());
        }

        
        
        
        }
    }//GEN-LAST:event_AddShipActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        Cheatingenabled=true;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void turntimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turntimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turntimeActionPerformed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void LoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGameActionPerformed
        choosenfile=jComboBox1.getSelectedItem().toString();
        this.setVisible(false);
        Loadgame=true;
        synchronized(Projectafterupdatev12.gamewaiter){
        Projectafterupdatev12.gamewaiter.notify();}
        
    }//GEN-LAST:event_LoadGameActionPerformed

    private void ScoreBoardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreBoardbtnActionPerformed
        // TODO add your handling code here:
        //i have to set the score board data
        ScoreBoard scoreboard=new ScoreBoard();
       // Map<String , Integer> map=new HashMap<String,Integer>();
        Map<String , Pair<Integer, Integer>> map1=new HashMap<String, Pair<Integer,Integer>>();
        
        File f=new File(new File("").getAbsolutePath()+"\\src\\projectafterupdatev1\\pkg2\\ScoreBoard");
        ObjectInputStream obj=null;
        try {
            obj= new ObjectInputStream(new FileInputStream(f));
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
        while(true){
        try {
            ScoreRecord temp=(ScoreRecord)obj.readObject();
            int ttt=0;
            if (temp.win==true)
                ttt=1;
            if (map1.containsKey(temp.name)==true){
                Pair<Integer,Integer> temp1;
                temp1 = new Pair<Integer,Integer>(map1.get(temp.name).getKey()+1,map1.get(temp.name).getValue());
                map1.put(temp.name,temp1);
            }   
            else
            {
                 Pair<Integer,Integer> temp1;
                temp1 = new Pair<Integer,Integer>(1,0);
                map1.put(temp.name, temp1);
            }
            if(ttt==1){
              Pair<Integer,Integer> temp1;  temp1 = new Pair<Integer,Integer>(map1.get(temp.name).getKey(),map1.get(temp.name).getValue()+1);
                map1.put(temp.name,temp1);
            }
                
        }catch(EOFException e){
            //System.out.println("EOF");
            try {
                obj.close();
            } catch (IOException ex) {
            }
            break;
        }catch (IOException ex) {System.out.println("IOE");
            } catch (ClassNotFoundException ex) {System.out.println("CLASs");
            }
      
        
        }
        //set the array list that will be used in score board table
        Object[][] object=new Object[map1.size()][4];
        SortedSet<String > set=new TreeSet<String>(map1.keySet());
        int i=0;
        for(String key:set){
            object[i][0]=key;
            object[i][1]=map1.get(key).getKey();
            object[i][2]=map1.get(key).getValue();
            Double wins=new Double(object[i][2]+"");
            
            Double freq=new Double(object[i][1]+"");
            
            object[i][3]=wins /freq;
            
            i++;
        }
        scoreboard.setData(object);
        scoreboard.sort();
        scoreboard.setVisible(true);
        
    }//GEN-LAST:event_ScoreBoardbtnActionPerformed

    private void GamesReordsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesReordsbtnActionPerformed
        // TODO add your handling code here:
        //add all your games records from the file to a list 
        List<FinishedGameRecord> gameslist=new ArrayList<FinishedGameRecord>();
       File f=new File(new File("").getAbsolutePath()+"\\src\\projectafterupdatev1\\pkg2\\GameRecords");
         ObjectInputStream obj=null;
        try {
            obj= new ObjectInputStream(new FileInputStream(f));
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
        while(true){
        try {
            FinishedGameRecord temp=(FinishedGameRecord)obj.readObject();
            gameslist.add(temp);
        }catch(EOFException e){
            //System.out.println("EOF");
            try {
                obj.close();
            } catch (IOException ex) {
            }
            break;
        }catch (IOException ex) {System.out.println("IOE");
            } catch (ClassNotFoundException ex) {System.out.println("CLASs");
            }
        }
        Object[][] temp=new Object[gameslist.size()-1][6];
        //loop without the begin 
        for(int i=1;i<gameslist.size();i++){
            temp[i-1][0]=gameslist.get(i).gameID;
            temp[i-1][1]=gameslist.get(i).nameoftheplayer;
            temp[i-1][2]=gameslist.get(i).nameoftheenemy;
            temp[i-1][3]=gameslist.get(i).theresult;
            temp[i-1][4]=gameslist.get(i).startadate;
            temp[i-1][5]=gameslist.get(i).enddate;
            
        }
        Games_Records gamesrecords=new Games_Records();
        gamesrecords.setData(temp);
        gamesrecords.sort();
        gamesrecords.setVisible(true);
        
    }//GEN-LAST:event_GamesReordsbtnActionPerformed

    private void GamesReordsbtnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_GamesReordsbtnAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_GamesReordsbtnAncestorAdded

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GameOptions().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GameOptions.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddShip;
    private javax.swing.JButton GamesReordsbtn;
    private javax.swing.JButton LoadGame;
    private javax.swing.JButton ScoreBoardbtn;
    private javax.swing.JTextField ShipsCounter;
    private javax.swing.JButton StartButton;
    private javax.swing.JTextField UserName;
    private javax.swing.JComboBox X1;
    private javax.swing.JComboBox X2;
    private javax.swing.JComboBox Y1;
    private javax.swing.JComboBox Y2;
    private javax.swing.JComboBox column;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox row;
    private javax.swing.JComboBox shipsnumber;
    private javax.swing.JComboBox turntime;
    // End of variables declaration//GEN-END:variables
}
