/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectafterupdatev1.pkg2;

/**
 *
 * @author Bassel
 */
public class WinnerDisplay extends javax.swing.JFrame {

    /**
     * Creates new form WinnerDisplay
     */
    public void setWinner(String s){
        winlabel.setText("The winner is "+s);
    }
    public WinnerDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winlabel = new javax.swing.JLabel();
        jLabel1Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(java.awt.Color.pink);
        setPreferredSize(new java.awt.Dimension(500, 210));
        getContentPane().setLayout(null);

        winlabel.setBackground(new java.awt.Color(255, 0, 0));
        winlabel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        winlabel.setForeground(new java.awt.Color(0, 255, 255));
        winlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(winlabel);
        winlabel.setBounds(20, 0, 450, 40);

        jLabel1Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectafterupdatev1/pkg2/x.gif.gif"))); // NOI18N
        getContentPane().add(jLabel1Background);
        jLabel1Background.setBounds(0, 0, 500, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinnerDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinnerDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinnerDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinnerDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinnerDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1Background;
    private javax.swing.JLabel winlabel;
    // End of variables declaration//GEN-END:variables
}
